# Generated by Django 5.1 on 2024-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('area_adscripcion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('nombre_acuerdo', models.CharField(max_length=250)),
                ('descripcion_avance', models.TextField(max_length=5000)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
    ]
