# Generated by Django 5.1 on 2024-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_acuerdo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acuerdo',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='area_adscripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
