# Generated by Django 5.1 on 2024-08-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_delete_acuerdo_alter_formulario_area_adscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='nombre_acuerdo',
        ),
        migrations.AddField(
            model_name='formulario',
            name='descripcion_acuerdo',
            field=models.CharField(default='hola', max_length=5000),
            preserve_default=False,
        ),
    ]
