# Generated by Django 5.1 on 2024-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_formulario_nombre_acuerdo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='descripcion_acuerdo',
            field=models.TextField(max_length=5000),
        ),
    ]
