# Generated by Django 5.1 on 2024-08-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_formulario_descripcion_acuerdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('area_adscripcion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion_avance', models.TextField(max_length=5000)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(editable=False, max_length=255, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('en_proceso', 'En Proceso'), ('sin_avance', 'Sin Avance'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('area_adscripcion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion_acuerdo', models.TextField(max_length=5000)),
                ('descripcion_avance', models.TextField(blank=True, max_length=5000, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('acuerdo_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='forms.acuerdo')),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='acuerdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='forms.acuerdo'),
        ),
    ]
