# Generated by Django 5.1 on 2024-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_actualizacion_acuerdo_delete_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='version',
            field=models.IntegerField(editable=False),
        ),
    ]
