# Generated by Django 5.1 on 2024-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_actualizacion_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='comision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='comision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
