# Generated by Django 5.1 on 2024-10-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_actualizacion_comision_actualizacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='minuta',
            field=models.FileField(blank=True, null=True, upload_to='minuta/'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='minuta',
            field=models.FileField(blank=True, null=True, upload_to='minuta/'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='fecha_creacion',
            field=models.CharField(max_length=100),
        ),
    ]
