# Generated by Django 5.1 on 2024-10-07 19:47

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_actualizacion_minuta_acuerdo_minuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.upload_to_documentos),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='minuta',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.upload_to_minuta),
        ),
    ]
