# Generated by Django 5.1 on 2024-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_acuerdo_documentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='minuta',
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='fecha_creacion',
            field=models.CharField(max_length=100),
        ),
    ]
