# Generated by Django 5.1 on 2024-10-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_remove_actualizacion_minuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
