# Generated by Django 5.1 on 2024-10-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_acuerdo_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='fecha_creacion',
            field=models.CharField(max_length=100),
        ),
    ]
