# Generated by Django 5.1 on 2024-10-08 03:06

import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_acuerdo_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='documentos',
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=forms.models.upload_to_documentos)),
                ('acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='forms.acuerdo')),
            ],
        ),
    ]
