# Generated by Django 5.1 on 2024-10-08 03:13

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_remove_actualizacion_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.upload_to_documentos),
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
