# Generated by Django 5.1 on 2024-10-08 03:21

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_actualizacion_documentos_acuerdo_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='minuta',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.upload_to_actualizacion_minuta),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.upload_to_actualizacion_documentos),
        ),
    ]
