# Generated by Django 5.1 on 2024-10-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_actualizacion_minuta_alter_actualizacion_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acuerdo',
            name='acuerdo_original',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='descripcion_avance',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='estado',
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='entidad',
            field=models.CharField(choices=[('CDMX', 'Ciudad de México'), ('EdoMex', 'Estado de México'), ('Hidalgo', 'Hidalgo')], default='CDMX', max_length=50),
            preserve_default=False,
        ),
    ]
