# Generated by Django 5.1 on 2024-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_remove_acuerdo_acuerdo_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdo',
            name='comision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
