# Generated by Django 5.1 on 2024-10-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_acuerdo_comision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='actualizacion',
            name='entidad',
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='estado',
            field=models.CharField(choices=[('CDMX', 'Ciudad de México'), ('EdoMex', 'Estado de México'), ('Hidalgo', 'Hidalgo')], default='CDMX', max_length=50),
            preserve_default=False,
        ),
    ]
