# Generated by Django 5.1 on 2024-10-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_remove_actualizacion_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='estatus_avance',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('sin_avance', 'Sin Avance'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=50),
        ),
    ]
