# Generated by Django 5.1 on 2024-10-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_actualizacion_estatus_avance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acuerdo',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='area_adscripcion',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='telefono',
        ),
    ]
