# Generated by Django 5.1 on 2024-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_remove_acuerdo_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdo',
            name='ZM',
            field=models.CharField(choices=[('ZMVM', 'Valle de México'), ('ZMPachuca', 'Pachuca'), ('ZMTulancingo', 'Tulancingo'), ('ZMTula', 'Tula'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=50),
        ),
    ]
