# Generated by Django 5.1 on 2024-10-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_acuerdo_zm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualizacion',
            old_name='area_adscripcion',
            new_name='cargo',
        ),
    ]
