# Generated by Django 5.1 on 2024-10-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_rename_area_adscripcion_actualizacion_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='estatus_avance',
        ),
    ]
