# Generated by Django 5.1 on 2024-10-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_remove_actualizacion_estatus_avance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acuerdo',
            old_name='ZM',
            new_name='zm',
        ),
    ]
