# Generated by Django 5.1 on 2024-11-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_rename_zm_acuerdo_zm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='zm',
            field=models.CharField(choices=[('ZMVM', 'Valle de México'), ('ZMPachuca', 'Pachuca'), ('ZMTulancingo', 'Tulancingo'), ('ZMTula', 'Tula'), ('no_aplica', 'No Aplica')], max_length=50),
        ),
    ]
